default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: root
  pool: 5
  timeout: 5000
  host: localhost
development:
  <<: *default
  database: ecommerce_development
test:
  <<: *default
  database: ecommerce_test
